Support graphql in backend
frontegg/create-saas pull request #35
Opened 2020-09-15 18:33 UTC by livnekes

2020-09-19 08:11 UTC, aviadmizrachi requested changes

2020-09-19 08:11 UTC, aviadmizrachi commented on backend/api-gw/src/server.ts
> +class AuthenticatedDataSource extends RemoteGraphQLDataSource {
Let's separate it to a different class

2020-09-19 08:11 UTC, aviadmizrachi commented on backend/services/metrics-service/src/db/seed/request.seed.ts
> +const IPS: string[] = ['208.80.235', '185.159.83.104', '208.97.177.47', '45.33.45.6'];
208.80.235 is not a valid IP V4

2020-09-19 11:52 UTC, livnekes commented on backend/api-gw/src/server.ts
> +class AuthenticatedDataSource extends RemoteGraphQLDataSource {
done

2020-09-19 11:52 UTC, livnekes commented on backend/services/metrics-service/src/db/seed/request.seed.ts
> +const IPS: string[] = ['208.80.235', '185.159.83.104', '208.97.177.47', '45.33.45.6'];
done

2020-09-21 09:44 UTC, aviadmizrachi approved these changes

2020-09-21 09:44 UTC, merged