add more frontend changes
frontegg/create-saas pull request #42
Opened 2020-09-23 13:45 UTC by livnekes

2020-09-23 16:59 UTC, aviadmizrachi requested changes

2020-09-23 16:59 UTC, aviadmizrachi commented on backend/api-gw/src/server.ts
>        apiKey: FRONTEGG_API_KEY,
Should use the authMiddleware

2020-09-24 06:16 UTC, livnekes commented on backend/api-gw/src/server.ts
>        apiKey: FRONTEGG_API_KEY,
done

2020-09-24 06:24 UTC, aviadmizrachi approved these changes

2020-09-24 06:25 UTC, aviadmizrachi approved these changes

2020-09-24 06:25 UTC, merged