more frontend refactoring
frontegg/create-saas pull request #55
Opened 2020-10-08 13:29 UTC by livnekes

2020-10-13 11:38 UTC, frontegg-david requested changes

2020-10-13 11:38 UTC, frontegg-david commented on frontend/Dockerfile
> +FROM nginx
`FROM nginx:1.19-alpine`

2020-10-13 11:38 UTC, frontegg-david commented on frontend/Dockerfile
> +COPY ./nginx.conf /etc/nginx/conf.d/default.conf
`COPY ./nginx.conf /etc/nginx/nginx.conf`

2020-10-13 11:38 UTC, frontegg-david commented on frontend/Dockerfile
> +FROM nginx
`FROM nginx:1.19-alpine`

2020-10-13 11:38 UTC, frontegg-david commented on frontend/Dockerfile
>  WORKDIR /app
you can remove

2020-10-13 11:38 UTC, frontegg-david commented on frontend/nginx.conf
> +    root /var/www/;
check this root

2020-10-13 11:38 UTC, frontegg-david commented on frontend/nginx.conf
> +        try_files $uri /index.html;
why using /index.html, replace with ./index.html or index.html

2020-10-13 11:38 UTC, frontegg-david commented on frontend/src/Components/DatePicker/DatePicker.tsx
>    header: string;
inline: boolean

2020-10-13 11:38 UTC, frontegg-david commented on frontend/src/Components/Pagination/Pagination.tsx
> +  last?: React.ReactElement | string;
change `React.ReactElement | string` to `React.ReactNode`

2020-10-13 11:38 UTC, frontegg-david commented on frontend/src/Pages/MainLayout/DatePickerPage/DatePickerPage.tsx
> +      type: 'inline',
change to inline without type

2020-10-13 11:38 UTC, frontegg-david commented on frontend/src/Pages/MainLayout/DatePickerPage/DatePickerPage.tsx
> +          Use the <code> &lt;Datepicker type='inline'/&gt;</code> component to display a datepicker
change to inline without type

2020-10-13 12:23 UTC, livnekes commented on frontend/nginx.conf
> +        try_files $uri /index.html;
doesn't work without the slash. don't know why ...

2020-10-15 08:24 UTC, frontegg-david approved these changes

2020-10-15 08:30 UTC, merged